site_name: Coffy Machine
site_url: https://github.com/sven1103/coffy-machine
theme:
  name: material
  palette:
    scheme: slate
    primary: brown
  features:
    - navigation.tabs
nav:
  - Home: index.md
  - Setup: setup.md
  - API: api.md
